#!/usr/bin/env node
/**
 * Generates one typed module per feature contract.
 *
 * Each feature keeps its own OpenAPI document (research.md R-006 of feature
 * 002), so this discovers every contract under specs/ rather than naming one.
 * A script that names a single file does not fail when a second contract
 * appears — it just quietly stops covering it, which is the failure this
 * replaces.
 */
import { execFileSync } from "node:child_process";
import { readdirSync, existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const specsDir = join(here, "..", "..", "specs");

const features = readdirSync(specsDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .filter((name) => existsSync(join(specsDir, name, "contracts", "openapi.yaml")))
  .sort();

if (features.length === 0) {
  console.error("No contracts found under specs/*/contracts/openapi.yaml");
  process.exit(1);
}

const modules = [];

for (const feature of features) {
  // "001-master-career-profile" -> "001"
  const number = feature.split("-")[0];
  const out = `./src/schema-${number}.ts`;
  const contract = join(specsDir, feature, "contracts", "openapi.yaml");

  console.log(`${feature} -> ${out}`);
  execFileSync("npx", ["openapi-typescript", contract, "-o", out], {
    cwd: here,
    stdio: "inherit",
  });

  modules.push({ number, feature });
}

const banner = `// Generated by generate.mjs. Do not edit by hand.
// One module per feature contract; see specs/*/contracts/openapi.yaml.
`;

const body = modules
  .map(
    ({ number, feature }) =>
      `// ${feature}\nexport type { paths as Paths${number}, components as Components${number} } from "./schema-${number}";`,
  )
  .join("\n\n");

// Feature 001 is the base surface, so its names stay unprefixed for the code
// that already imports them.
const compat = `\n\n// Feature 001's names, unprefixed, for existing callers.\nexport type { paths, components } from "./schema-001";\n`;

writeFileSync(join(here, "src", "index.ts"), banner + "\n" + body + compat);
console.log(`Wrote src/index.ts re-exporting ${modules.length} contract(s)`);
