"""resume import

Revision ID: 69a2484ffcfc
Revises: 83e139f47e42
Create Date: 2026-09-25 11:39:51.342576
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '69a2484ffcfc'
down_revision: str | None = '83e139f47e42'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import',
    sa.Column('source_kind', sa.Enum('pasted_text', 'pdf', 'docx', name='import_source_kind'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='import_status'), server_default='pending', nullable=False),
    sa.Column('failure_reason', sa.Enum('unreadable_document', 'unsupported_format', 'no_career_information', 'service_unavailable', 'extraction_failed', name='import_failure_reason'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_profile_id'), 'import', ['profile_id'], unique=False)
    op.create_index(op.f('ix_import_status'), 'import', ['status'], unique=False)
    op.add_column('proposed_entry', sa.Column('import_id', sa.UUID(), nullable=True))
    op.add_column('proposed_entry', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('proposed_entry', sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_proposed_entry_import_id'), 'proposed_entry', ['import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposed_entry_import_id'), table_name='proposed_entry')
    op.drop_column('proposed_entry', 'conflicts')
    op.drop_column('proposed_entry', 'evidence')
    op.drop_column('proposed_entry', 'import_id')
    op.drop_index(op.f('ix_import_status'), table_name='import')
    op.drop_index(op.f('ix_import_profile_id'), table_name='import')
    op.drop_table('import')
    # ### end Alembic commands ###
