"""proposed entries

Revision ID: 83e139f47e42
Revises: e541dac9bd2f
Create Date: 2026-09-20 21:29:52.929490
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '83e139f47e42'
down_revision: str | None = 'e541dac9bd2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposed_entry',
    sa.Column('entry_type', sa.Enum('work_experience', 'education', 'certification', 'skill', 'language', 'career_story', name='proposed_entry_type'), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='proposal_status'), server_default='pending', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('possible_duplicate_of', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_entry_profile_id'), 'proposed_entry', ['profile_id'], unique=False)
    op.create_index(op.f('ix_proposed_entry_status'), 'proposed_entry', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposed_entry_status'), table_name='proposed_entry')
    op.drop_index(op.f('ix_proposed_entry_profile_id'), table_name='proposed_entry')
    op.drop_table('proposed_entry')
    # ### end Alembic commands ###
