"""identity date of birth and address

Revision ID: 9bb1dd002f90
Revises: 69a2484ffcfc
Create Date: 2026-10-02 16:41:23.670707
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9bb1dd002f90'
down_revision: str | None = '69a2484ffcfc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('identity', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity', 'address')
    op.drop_column('identity', 'date_of_birth')
    # ### end Alembic commands ###
