// Generated by generate.mjs. Do not edit by hand.
// One module per feature contract; see specs/*/contracts/openapi.yaml.

// 001-master-career-profile
export type { paths as Paths001, components as Components001 } from "./schema-001";

// 002-ai-resume-import
export type { paths as Paths002, components as Components002 } from "./schema-002";

// Feature 001's names, unprefixed, for existing callers.
export type { paths, components } from "./schema-001";
