/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/profile/documents/shokumu-keirekisho/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What is missing before generating
         * @description Reports what a document would lack, so the user can fix it first rather than discover it after printing. Also names the achievements recorded against no employer, which will appear in the closing section.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessReport"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                /** @description No profile exists yet for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/documents/shokumu-keirekisho": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a 職務経歴書
         * @description Produces the document and streams it. Nothing is retained: the profile and the snapshot of what was used are what persist.
         *     With `preview=true` the same document is returned for display rather than download. The content is identical — only the disposition differs, so a user never previews one thing and downloads another.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Return the document for display rather than as a download. */
                    preview?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ShokumuKeirekishoRequest"];
                };
            };
            responses: {
                /** @description The document */
                200: {
                    headers: {
                        /** @description `attachment` by default, `inline` when previewing. */
                        "Content-Disposition"?: string;
                        /** @description How many pages the document runs to. A long career produces more pages rather than losing entries, and the interface uses this to say so. */
                        "X-Document-Pages"?: number;
                        /** @description The snapshot recording what this document was based on, so its statements stay traceable after the entries change. */
                        "X-Snapshot-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                401: components["responses"]["Unauthorised"];
                /** @description No profile exists yet for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description The profile lacks something a document cannot be meaningful without — a name, or any work history at all. The response names what is missing rather than producing a document with it blank. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        ValidationError: {
            code: string;
            message: string;
            failures: {
                field: string;
                reason: string;
            }[];
        };
        /**
         * @description Which calendar the dates are written in. One convention is used throughout a document; the two never appear together.
         * @default seireki
         * @enum {string}
         */
        DateConvention: "seireki" | "wareki";
        /**
         * @default a4
         * @enum {string}
         */
        PaperSize: "a4" | "b5";
        /**
         * @description The order the employer sections run in. Both carry the identical set of entries; only the order differs. Grouping by project is not offered — the profile holds no project entity, and a career story has no client, period or role to build one from.
         * @default reverse_chronological
         * @enum {string}
         */
        Arrangement: "reverse_chronological" | "chronological";
        /** @description The conventions chosen for this document. None affects what the document says, only how it reads. */
        ShokumuKeirekishoRequest: {
            arrangement?: components["schemas"]["Arrangement"];
            date_convention?: components["schemas"]["DateConvention"];
            paper_size?: components["schemas"]["PaperSize"];
        };
        /** @description What a document would lack. Separates what cannot be left out from what will simply be blank, because the two need different responses. */
        ReadinessReport: {
            /** @description False only when something essential is absent. */
            can_generate: boolean;
            /** @description Fields without which a document is not meaningful. */
            missing_required: string[];
            /** @description Sections that will be blank. Listed rather than silently omitted, so nothing is a surprise after printing. */
            missing_optional: string[];
            /** @description Achievements recorded against no employer. They appear in the closing section rather than under an employer; the user may attach them to one, and this feature does not guess. */
            unattached_achievements: components["schemas"]["UnattachedAchievement"][];
        };
        UnattachedAchievement: {
            /** Format: uuid */
            entry_id: string;
            title: string;
        };
    };
    responses: {
        /** @description No verified identity */
        Unauthorised: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
