/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/profile/documents/rirekisho/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What is missing before generating
         * @description Reports what a document would lack, so the user can fix it first rather than discover it after printing. Also names the entries written in English, which will appear in English — the user may add a Japanese version to their profile, which this feature does not write for them (research.md R-001).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessReport"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                /** @description No profile exists yet for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/documents/rirekisho": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a 履歴書
         * @description Produces the document and streams it. Nothing is retained: the profile and the snapshot of what was used are what persist (FR-005, FR-016).
         *     With `preview=true` the same document is returned for display rather than download. The content is identical — only the disposition differs, so a user never previews one thing and downloads another.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Return the document for display rather than as a download. */
                    preview?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RirekishoRequest"];
                };
            };
            responses: {
                /** @description The document */
                200: {
                    headers: {
                        /** @description `attachment` by default, `inline` when previewing. */
                        "Content-Disposition"?: string;
                        /** @description How many pages the document runs to. A history that does not fit the conventional two produces more pages rather than losing entries (FR-018a), and the interface uses this to say so. */
                        "X-Document-Pages"?: number;
                        /** @description The snapshot recording what this document was based on, so its statements stay traceable after the entries change (FR-016). */
                        "X-Snapshot-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                401: components["responses"]["Unauthorised"];
                /** @description No profile exists yet for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description The profile lacks something a document cannot be meaningful without — a name above all. The response names what is missing rather than producing a document with it blank (FR-015). */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        ValidationError: {
            code: string;
            message: string;
            failures: {
                field: string;
                reason: string;
            }[];
        };
        /**
         * @description Which calendar the dates are written in. One convention is used throughout a document; the two never appear together (FR-019).
         * @default seireki
         * @enum {string}
         */
        DateConvention: "seireki" | "wareki";
        /**
         * @default a4
         * @enum {string}
         */
        PaperSize: "a4" | "b5";
        /** @description The conventions chosen for this document. Neither affects what the document says, only how it reads. */
        RirekishoRequest: {
            date_convention?: components["schemas"]["DateConvention"];
            paper_size?: components["schemas"]["PaperSize"];
        };
        /** @description What a document would lack. Separates what cannot be left out from what will simply be blank, because the two need different responses from the user. */
        ReadinessReport: {
            /** @description False only when something essential is absent. */
            can_generate: boolean;
            /** @description Fields without which a document is not meaningful, named so the user can supply them (FR-015). */
            missing_required: string[];
            /** @description Fields that will be blank in the document. Listed rather than silently omitted, so nothing is a surprise after printing (FR-022c). */
            missing_optional: string[];
            /** @description Entries written in English, which will appear in English. The user may add a Japanese version to their profile; this feature does not write one for them. */
            entries_without_japanese: components["schemas"]["EnglishEntry"][];
        };
        EnglishEntry: {
            /** Format: uuid */
            entry_id: string;
            /** @enum {string} */
            entry_type: "work_experience" | "education" | "certification";
            /** @description How the entry reads now, so the user can recognise it. */
            label: string;
        };
    };
    responses: {
        /** @description No verified identity */
        Unauthorised: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
