/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/profile/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List this profile's imports
         * @description The minimal record kept after review, so a user can see where an entry in their profile came from (FR-019a). Carries no filename (FR-019b).
         */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["ImportStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Imports, most recent first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Import"][];
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        put?: never;
        /**
         * Import career information from pasted text
         * @description Extraction begins immediately. If it completes within the deadline the response carries a terminal status; otherwise it returns `running` and the client polls this import until it settles (research.md R-002).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Any free text describing the user's career */
                        text: string;
                    };
                };
            };
            responses: {
                /** @description Import created; check `status` for whether it has finished */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Import"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/imports/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import career information from a PDF or DOCX
         * @description The document is read into memory, its text extracted, and its bytes released. It is never written to disk or object storage (FR-004, research.md R-005), so there is nothing to delete afterwards.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description A PDF or DOCX document
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Import created; check `status` for whether it has finished */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Import"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                /** @description The document is larger than this feature accepts */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not a format this feature accepts. Distinguished from a document that is the right format but cannot be read (FR-003). */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        /**
         * Follow an import to its outcome
         * @description Polled while an import is running. Always reaches a terminal status (SC-007), whether it finished in the request or in the background.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    import_id: components["parameters"]["ImportId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The import */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportDetail"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/imports/{import_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abandon an import before its proposals reach review
         * @description Supports FR-018 — a user may abandon an import they started.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    import_id: components["parameters"]["ImportId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelled; no proposals were created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Import"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
                /** @description Already finished; there is nothing to abandon */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        ValidationError: {
            code: string;
            message: string;
            failures: {
                field: string;
                reason: string;
            }[];
        };
        /** @enum {string} */
        ImportStatus: "pending" | "running" | "completed" | "failed";
        /** @enum {string} */
        SourceKind: "pasted_text" | "pdf" | "docx";
        /**
         * @description Why an import failed. The values separate outcomes that look alike to a user but have different remedies: a document that cannot be read will never succeed, while an unavailable service is worth trying later (FR-017b).
         * @enum {string}
         */
        FailureReason: "unreadable_document" | "unsupported_format" | "no_career_information" | "service_unavailable" | "extraction_failed";
        /** @description The record kept after review. Carries no filename, by decision — a name can reveal where someone was applying (FR-019b). */
        Import: {
            /** Format: uuid */
            id: string;
            source_kind: components["schemas"]["SourceKind"];
            status: components["schemas"]["ImportStatus"];
            failure_reason?: components["schemas"]["FailureReason"] | null;
            /** Format: date-time */
            started_at: string;
            completed_at?: string | null;
            /** @description Proposals created. Zero is a valid completed outcome. */
            entry_count: number;
        };
        ImportDetail: components["schemas"]["Import"] & {
            outcome?: components["schemas"]["ExtractionOutcome"] | null;
        };
        /** @description What was found, and what was looked for and not found (FR-016). */
        ExtractionOutcome: {
            /** @description Count of entries proposed, by kind */
            found?: {
                [key: string]: number;
            };
            /** @description Kinds of career information the source did not contain, so a user can see what is missing rather than assume it was lost. */
            not_found?: string[];
            /** @description A plain explanation the user can act on */
            message?: string;
        };
        /** @description The passage of source text a value was taken from. A field appears here only if its quote was verified against the source; a field whose quote could not be found is absent from the proposal entirely (FR-008). */
        FieldEvidence: {
            /** @description The passage from the source document */
            quote: string;
            /** @description Always true in stored evidence. Present so the shape is explicit about what the verifier decided. */
            verified: boolean;
        };
        /** @description A disagreement within the source. Flagged, never resolved: choosing the more likely reading would mean deciding what a user's career was (FR-012b). */
        Conflict: {
            fields: string[];
            reason: string;
        };
    };
    responses: {
        /** @description No verified identity */
        Unauthorised: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such import in the caller's profile */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The submitted values were rejected, with the offending field named */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationError"];
            };
        };
    };
    parameters: {
        ImportId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
