/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the caller's profile with every section */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                /** @description No profile exists yet for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete the profile
         * @description Erases residence status, nationality, visa type and visa expiry immediately and unrecoverably. All remaining data is retained for a 30-day recovery window, then permanently erased (FR-024, FR-025). The response states what was erased and when the window closes, so the client can satisfy FR-026 before calling.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deletion accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeletionReceipt"];
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update profile-level settings
         * @description Currently the interface locale only. Changing it never alters stored content (FR-023).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        interface_locale?: components["schemas"]["Locale"];
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        trace?: never;
    };
    "/profile/completeness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report which sections are empty
         * @description Supports FR-015 — an incomplete profile is valid and reportable.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Section-by-section completeness */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: {
                                complete?: boolean;
                                entry_count?: number;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a profile inside its recovery window
         * @description Recovers everything still held. Does not recover the immediately-erased Japan-specific fields, which no longer exist.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Restored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                /** @description The recovery window has passed; the profile is gone */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export the complete profile
         * @description Returns one archive containing a complete structured data file and a readable document of the same profile (FR-035, FR-036). Japan-specific fields are included regardless of their disclosure settings (FR-037), because those settings govern generated documents rather than the user's own copy. The archive is streamed and not retained server-side (R-005).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The export archive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the identity section */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Identity"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/japan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the Japan-specific section
         * @description Every field is optional. Disclosure flags default to false and govern whether a field may appear in a generated document (FR-006).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JapanProfile"];
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JapanProfile"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the career preferences section */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CareerPreference"];
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CareerPreference"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List work experiences */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Experiences, most recent first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkExperience"][];
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        put?: never;
        /** Add a work experience */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkExperienceInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkExperience"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/experiences/{experience_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: components["parameters"]["ExperienceId"];
            };
            cookie?: never;
        };
        /** Get one work experience, with its linked career stories */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    experience_id: components["parameters"]["ExperienceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The experience */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkExperienceDetail"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a work experience
         * @description FR-013 requires the user be told what references this entry before it is removed. Call without `confirm` to receive the references; call again with `confirm=true` to proceed.
         */
        delete: {
            parameters: {
                query?: {
                    confirm?: boolean;
                };
                header?: never;
                path: {
                    experience_id: components["parameters"]["ExperienceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
                /** @description Confirmation required; the body lists what references this entry */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReferenceWarning"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a work experience */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    experience_id: components["parameters"]["ExperienceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkExperienceInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkExperience"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        trace?: never;
    };
    "/profile/education": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List education entries */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Education entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Education"][];
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        put?: never;
        /** Add an education entry */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Education"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Education"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/education/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an education entry */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entry_id: components["parameters"]["EntryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update an education entry */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entry_id: components["parameters"]["EntryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Education"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Education"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        trace?: never;
    };
    "/profile/certifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List certifications */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Certifications */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Certification"][];
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        put?: never;
        /** Add a certification */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Certification"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Certification"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/certifications/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a certification */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entry_id: components["parameters"]["EntryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update a certification */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entry_id: components["parameters"]["EntryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Certification"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Certification"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/profile/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List skills */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Skills */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Skill"][];
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        put?: never;
        /** Add a skill, optionally linked to the experiences where it was used */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Skill"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/skills/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a skill */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entry_id: components["parameters"]["EntryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update a skill */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entry_id: components["parameters"]["EntryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Skill"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/profile/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List languages */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Languages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Language"][];
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        put?: never;
        /** Add a language with its proficiency */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Language"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Language"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/languages/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a language */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entry_id: components["parameters"]["EntryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update a language */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entry_id: components["parameters"]["EntryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Language"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Language"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/profile/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List career stories, optionally filtered by keyword */
        get: {
            parameters: {
                query?: {
                    /** @description Keyword search across title, challenge, action and result */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching stories */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CareerStory"][];
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        put?: never;
        /** Add a career story */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CareerStoryInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CareerStory"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a career story */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    story_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update a career story */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    story_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CareerStoryInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CareerStory"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/profile/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List entries awaiting review
         * @description Proposals are not part of the profile and appear in no other read (FR-018). Each carries the source it came from and any possible duplicate detected against existing entries.
         */
        get: {
            parameters: {
                query?: {
                    status?: "pending" | "accepted" | "rejected";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Proposals */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProposedEntry"][];
                    };
                };
                401: components["responses"]["Unauthorised"];
            };
        };
        put?: never;
        /**
         * Submit proposed entries from a source
         * @description The contract an import feature delivers into. Accepting proposals here does not add anything to the profile; only review does.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProposedEntryInput"][];
                };
            };
            responses: {
                /** @description Queued for review, with any possible duplicates flagged */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProposedEntry"][];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/proposals/{proposal_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a proposal, optionally with edits
         * @description When a corrected payload is supplied, the corrected version becomes the profile entry and the original proposal content is not retained as profile data (FR-019).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    proposal_id: components["parameters"]["ProposalId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description The corrected content, replacing what was proposed */
                        payload?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description Accepted; the created profile entry is returned */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AcceptedProposal"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
                /** @description Already reviewed; accepted and rejected are terminal */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a proposal */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    proposal_id: components["parameters"]["ProposalId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rejected; nothing enters the profile */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
                /** @description Already reviewed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/proposals/{proposal_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge a proposal into an existing entry
         * @description Never automatic. The user chooses to merge; keeping both as separate entries is always available by accepting instead (FR-034).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    proposal_id: components["parameters"]["ProposalId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        target_entry_id: string;
                        /** @description The merged content to write to the target entry */
                        payload?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description Merged; the updated entry is returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkExperience"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
                /** @description Already reviewed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture an immutable snapshot of the entries a document drew on
         * @description Called by a document-generating feature at the moment of generation, so the claims in that document stay traceable after the entries change (FR-028).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        document_ref: string;
                        entry_ids: string[];
                    };
                };
            };
            responses: {
                /** @description Captured */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntrySnapshot"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        /**
         * Read a snapshot
         * @description Returns the captured content unchanged, whether or not the entries it captured still exist (FR-029). Snapshots are never updated or deleted individually.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    snapshot_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntrySnapshot"];
                    };
                };
                401: components["responses"]["Unauthorised"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Interface language, or the language an entry was authored in
         * @enum {string}
         */
        Locale: "en" | "ja";
        Error: {
            code: string;
            message: string;
        };
        ValidationError: {
            code: string;
            message: string;
            failures: {
                field: string;
                reason: string;
            }[];
        };
        /** @description What references an entry the user is about to delete (FR-013) */
        ReferenceWarning: {
            message?: string;
            references?: {
                kind?: string;
                count?: number;
            }[];
        };
        DeletionReceipt: {
            /** @description Fields destroyed on the request path, unrecoverable */
            erased_immediately?: string[];
            /** Format: date-time */
            recoverable_until?: string;
        };
        /** @description The whole profile. See ../data-model.md for field rules. */
        Profile: {
            /** Format: uuid */
            id?: string;
            interface_locale?: components["schemas"]["Locale"];
            identity?: components["schemas"]["Identity"];
            japan?: components["schemas"]["JapanProfile"];
            preferences?: components["schemas"]["CareerPreference"];
            experiences?: components["schemas"]["WorkExperience"][];
            education?: components["schemas"]["Education"][];
            certifications?: components["schemas"]["Certification"][];
            skills?: components["schemas"]["Skill"][];
            languages?: components["schemas"]["Language"][];
        };
        Identity: {
            full_name_latin: string;
            full_name_japanese?: string | null;
            furigana?: string | null;
            email?: string | null;
            phone?: string | null;
        };
        /** @description Every field optional. Disclosure flags default false and govern whether a field may appear in a generated document (FR-006); they do not affect export (FR-037). */
        JapanProfile: {
            residence_status?: string | null;
            nationality?: string | null;
            visa_type?: string | null;
            /** Format: date */
            visa_expires_on?: string | null;
            work_authorisation?: boolean | null;
            japanese_qualification?: string | null;
            /** @default false */
            disclose_residence_status: boolean;
            /** @default false */
            disclose_nationality: boolean;
            /** @default false */
            disclose_visa: boolean;
            /** @default false */
            disclose_work_authorisation: boolean;
            /** @default false */
            disclose_japanese_qualification: boolean;
        };
        WorkExperienceInput: {
            employer_name: string;
            job_title: string;
            /** @enum {string} */
            employment_type?: "permanent" | "contract" | "part_time" | "internship" | "freelance";
            /** Format: date */
            started_on: string;
            /**
             * Format: date
             * @description Null means ongoing
             */
            ended_on?: string | null;
            description?: string;
            source_language: components["schemas"]["Locale"];
        };
        WorkExperience: components["schemas"]["WorkExperienceInput"] & {
            /** Format: uuid */
            id: string;
        };
        WorkExperienceDetail: components["schemas"]["WorkExperience"] & {
            stories?: components["schemas"]["CareerStory"][];
        };
        Education: {
            /** Format: uuid */
            readonly id?: string;
            institution: string;
            qualification?: string | null;
            field_of_study?: string | null;
            /** Format: date */
            started_on?: string | null;
            /** Format: date */
            ended_on?: string | null;
            source_language?: components["schemas"]["Locale"];
        };
        Certification: {
            /** Format: uuid */
            readonly id?: string;
            name: string;
            issuer?: string | null;
            /** Format: date */
            issued_on?: string | null;
            /** Format: date */
            expires_on?: string | null;
            source_language?: components["schemas"]["Locale"];
        };
        Skill: {
            /** Format: uuid */
            readonly id?: string;
            name: string;
            /** @enum {string|null} */
            level?: "beginner" | "intermediate" | "advanced" | "expert" | null;
            used_in_experience_ids?: string[];
        };
        Language: {
            /** Format: uuid */
            readonly id?: string;
            language: string;
            /** @enum {string} */
            proficiency: "native" | "business" | "conversational" | "basic";
            qualification?: string | null;
        };
        CareerPreference: {
            desired_roles?: string[];
            desired_locations?: string[];
            /** @enum {string|null} */
            working_arrangement?: "onsite" | "hybrid" | "remote" | null;
            salary_min?: number | null;
            salary_max?: number | null;
            currency?: string | null;
            source_language?: components["schemas"]["Locale"];
        };
        CareerStoryInput: {
            /** Format: uuid */
            work_experience_id?: string | null;
            title: string;
            challenge: string;
            action: string;
            result: string;
            source_language: components["schemas"]["Locale"];
        };
        CareerStory: components["schemas"]["CareerStoryInput"] & {
            /** Format: uuid */
            id: string;
        };
        ProposedEntryInput: {
            /** @enum {string} */
            entry_type: "work_experience" | "education" | "certification" | "skill" | "language" | "career_story";
            /** @description Which source produced this proposal (FR-017) */
            source: string;
            /** @description The proposed content, shaped by entry_type */
            payload: Record<string, never>;
        };
        ProposedEntry: components["schemas"]["ProposedEntryInput"] & {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "rejected";
            /**
             * Format: uuid
             * @description Set when an existing entry shares the employer and an overlapping date range (FR-032). A suggestion only.
             */
            possible_duplicate_of?: string | null;
            /** Format: date-time */
            reviewed_at?: string | null;
            /**
             * Format: uuid
             * @description The import that created this proposal, where one did.
             */
            import_id?: string | null;
            /** @description Per field, the passage of source text the value came from. A field appears only if that passage was verified against the source; an unverifiable field is absent from the proposal entirely. Cleared when the proposal is reviewed, because afterwards it is a fragment of a resume with no purpose left. */
            evidence?: {
                [key: string]: {
                    /** @description The passage of source text this value was taken from */
                    quote: string;
                    verified: boolean;
                };
            } | null;
            /** @description Fields whose values disagree within the source. Flagged, never resolved: choosing the likelier reading would mean deciding what a user's career was. */
            conflicts?: {
                fields: string[];
                reason: string;
            }[] | null;
        };
        AcceptedProposal: {
            /** Format: uuid */
            proposal_id?: string;
            /** Format: uuid */
            created_entry_id?: string;
            entry_type?: string;
        };
        /** @description Immutable once created (FR-029) */
        EntrySnapshot: {
            /** Format: uuid */
            id?: string;
            document_ref?: string;
            /** Format: date-time */
            captured_at?: string;
            captured_entry_ids?: string[];
            /** @description The captured entries as they read at capture time */
            payload?: Record<string, never>;
        };
    };
    responses: {
        /** @description No verified identity */
        Unauthorised: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such entry in the caller's profile */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The submitted values were rejected. The response names the offending field and explains why, so the interface can show the reason rather than a generic failure (FR-014). */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationError"];
            };
        };
    };
    parameters: {
        ExperienceId: string;
        EntryId: string;
        ProposalId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
